apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management-agent-klusterlet-registration
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clusterclaims
  verbs:
  - get
  - list
  - watch
