apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-manager-registration-controller-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-manager-registration-controller-clusterrole
subjects:
- kind: ServiceAccount
  name: cluster-manager-registration-controller-sa
  namespace: open-cluster-management-hub
