apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2021-04-04T15:02:02Z"
  labels:
    olm.opgroup.permissions/aggregate-to-762dbf946e2b6240-view: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: klusterlets.operator.open-cluster-management.io-v1-view
rules:
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - klusterlets
  verbs:
  - get
  - list
  - watch
