apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klusterlets.operator.open-cluster-management.io-v1-edit
rules:
- apiGroups:
  - operator.open-cluster-management.io
  resources:
  - klusterlets
  verbs:
  - create
  - update
  - patch
  - delete
